import serial 
import time
ser = serial.Serial('/dev/ttyAMA0',115200,timeout =10)
time.sleep(0.1)

#init  MIP in serial mode
ser.write(b'\xFF')

time.sleep(0.1)
ser.write(b'\x06')
ser.write(b'\xFE')
ser.write(b'\x10')
ser.write(b'\x21')
ser.write(b'\x10')
ser.write(b'\x21')
ser.write(b'\x10')
ser.write(b'\x21')
ser.write(b'\x10')
ser.write(b'\x21')
ser.write(b'\x10')
ser.write(b'\x21')
ser.write(b'\x10')
#ser.write(b'\x21')
#ser.write(b'\x10')
#ser.write(b'\x21')
print(ser.name)
print(ser.isOpen())
ser.write(b'\xFFE0')
#ser.write(b'\xE0')
ser.write(b'\x14')
line = ser.read(4)
print (line)

ser.write(b'\x19')
line = ser.read(2)
print (line)
#ser.write(b'\x10')
#ser.write(b'\x00')
#ser.write(b'\x21')
#ser.write(b'\x10')
#ser.write(b'\x06')
time.sleep(10)
#ser.write(b'\xFA')
#ser.flush()
